/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    Conf: typeof import('./src/components/Conf.vue')['default']
    EmptyArea: typeof import('./src/components/EmptyArea.vue')['default']
    Header: typeof import('./src/components/Header.vue')['default']
    List: typeof import('./src/components/List.vue')['default']
    Match: typeof import('./src/components/Match.vue')['default']
    Ranking: typeof import('./src/components/Ranking.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
