name: Tag from package.json version

on:
  push:
    branches:
      - main

permissions:
  contents: write
  id-token: write
  actions: write

jobs:
  tag:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # タグ作成にはフル履歴が必要

      - name: Read version from package.json
        id: version
        run: |
          VERSION=$(jq -r '.version' package.json)
          echo "version=$VERSION" >> $GITHUB_OUTPUT

      - name: Check if tag already exists
        id: check_tag
        run: |
          TAG="v${{ steps.version.outputs.version }}"
          if git rev-parse "$TAG" >/dev/null 2>&1; then
            echo "Tag $TAG already exists."
            echo "tag_exists=true" >> $GITHUB_OUTPUT
          else
            echo "Creating new tag: $TAG"
            echo "tag_exists=false" >> $GITHUB_OUTPUT
          fi

      - name: Create and push tag with PAT
        if: steps.check_tag.outputs.tag_exists == 'false'
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          TAG="v${{ steps.version.outputs.version }}"
          git tag "$TAG"
          git push https://x-access-token:${{ secrets.GH_PAT }}@github.com/${{ github.repository }} "$TAG"
