import type { Rank } from "@/types/rank";

export const rankOptions: Rank[] = [
  { name: "", value: 99 },
  { name: "9段", value: -9 },
  { name: "8段", value: -8 },
  { name: "7段", value: -7 },
  { name: "6段", value: -6 },
  { name: "5段", value: -5 },
  { name: "4段", value: -4 },
  { name: "3段", value: -3 },
  { name: "2段", value: -2 },
  { name: "初段", value: -1 },
  { name: "1級", value: 1 },
  { name: "2級", value: 2 },
  { name: "3級", value: 3 },
  { name: "4級", value: 4 },
  { name: "5級", value: 5 },
  { name: "6級", value: 6 },
  { name: "7級", value: 7 },
  { name: "8級", value: 8 },
  { name: "9級", value: 9 },
  { name: "10級", value: 10 },
  { name: "11級", value: 11 },
  { name: "12級", value: 12 },
  { name: "13級", value: 13 },
  { name: "14級", value: 14 },
  { name: "15級", value: 15 },
  { name: "16級", value: 16 },
  { name: "17級", value: 17 },
  { name: "18級", value: 18 },
  { name: "19級", value: 19 },
  { name: "20級", value: 20 },
];